# reference: http://www.objc.io/issue-6/travis-ci.html

language: objective-c
osx_image: xcode8
env:
  global:
    - LC_CTYPE=en_US.UTF-8
    - LANG=en_US.UTF-8
    - PROJECT=SwinjectPropertyLoader.xcodeproj
    - IOS_SDK=iphonesimulator10.0
    - OSX_SDK=macosx10.11
    - TVOS_SDK=appletvsimulator10.0
    - WATCHOS_SDK=watchsimulator3.0
  matrix:
    - DESTINATION="OS=8.4,name=iPhone 5S" SCHEME="SwinjectPropertyLoader-iOS" SDK="$IOS_SDK" PLATFORM="iOS" POD_LINT="NO" ACTION="test"
    - DESTINATION="OS=9.3,name=iPhone 6" SCHEME="SwinjectPropertyLoader-iOS" SDK="$IOS_SDK" PLATFORM="iOS" POD_LINT="NO" ACTION="test"
    - DESTINATION="OS=10.0,name=iPhone 6S Plus" SCHEME="SwinjectPropertyLoader-iOS" SDK="$IOS_SDK" PLATFORM="iOS" POD_LINT="YES" ACTION="test"
    - DESTINATION="arch=x86_64" SCHEME="SwinjectPropertyLoader-OSX" SDK="$OSX_SDK" PLATFORM="Mac" POD_LINT="NO" ACTION="test" ACTION="test"
    - DESTINATION="OS=9.2,name=Apple TV 1080p" SCHEME="SwinjectPropertyLoader-tvOS" SDK="$TVOS_SDK" PLATFORM="tvOS" POD_LINT="NO" ACTION="test"
    - DESTINATION="OS=10.0,name=Apple TV 1080p" SCHEME="SwinjectPropertyLoader-tvOS" SDK="$TVOS_SDK" PLATFORM="tvOS" POD_LINT="NO" ACTION="test"
    - DESTINATION="OS=2.2,name=Apple Watch - 42mm" SCHEME="SwinjectPropertyLoader-watchOS" SDK="$WATCHOS_SDK" PLATFORM="watchOS" POD_LINT="NO" ACTION="build"
    - DESTINATION="OS=3.0,name=Apple Watch - 42mm" SCHEME="SwinjectPropertyLoader-watchOS" SDK="$WATCHOS_SDK" PLATFORM="watchOS" POD_LINT="NO" ACTION="build"

before_install:
  - git submodule update --recursive
script:
  - set -o pipefail
  - xcodebuild -version
  - open -b com.apple.iphonesimulator # Workaround https://github.com/travis-ci/travis-ci/issues/3040
  - xcodebuild -project "$PROJECT" -scheme "$SCHEME" -sdk "$SDK" -destination "$DESTINATION" 
    -configuration Debug ONLY_ACTIVE_ARCH=NO $ACTION
  - xcodebuild -project "$PROJECT" -scheme "$SCHEME" -sdk "$SDK" -destination "$DESTINATION" 
    -configuration Release ONLY_ACTIVE_ARCH=NO $ACTION
# Uncomment later
#  - if [ $POD_LINT == "YES" ]; then
#      pod lib lint --quick;
#    fi
notifications:
  email:
    on_success: never
